name: Deploy Frontend + Backend via FTP Locaweb

on:
  push:
    branches:
      - main

jobs:
  deploy-frontend:
    name: Deploy Frontend React
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Build React app
        working-directory: frontend
        run: |
          npm install
          npm run build

      - name: Upload frontend via FTP
        uses: locaweb/ftp-deploy@1.0.0
        with:
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USER }}
          password: ${{ secrets.PASS }}
          localDir: frontend/dist
          remoteDir: public_html

  deploy-backend:
    name: Deploy Backend PHP
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Instalar dependências PHP (composer install)
        run: composer install --no-dev --optimize-autoloader

      - name: Criar arquivo .env para backend
        run: |
          echo "DB_HOST=${{ secrets.DB_HOST }}" > backend/.env
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> backend/.env
          echo "DB_USER=${{ secrets.DB_USER }}" >> backend/.env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> backend/.env
          echo "API_KEY=${{ secrets.API_KEY }}" >> backend/.env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> backend/.env

      # - name: Upload .env via FTP
      #   uses: locaweb/ftp-deploy@1.0.0
      #   with:
      #     host: ${{ secrets.HOST }}
      #     user: ${{ secrets.USER }}
      #     password: ${{ secrets.PASS }}
      #     localDir: backend/.env
      #     remoteDir: app
      # Se o locaweb/ftp-deploy aceitar, pode usar include: '.env'
      # Caso contrário, ele enviará tudo de backend, que inclui .env e backend/app.

      - name: Upload backend via FTP
        uses: locaweb/ftp-deploy@1.0.0
        with:
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USER }}
          password: ${{ secrets.PASS }}
          localDir: backend
          remoteDir: app

      - name: Upload vendor/ via FTP
        uses: locaweb/ftp-deploy@1.0.0
        with:
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USER }}
          password: ${{ secrets.PASS }}
          localDir: vendor
          remoteDir: vendor

      - name: Upload index.php via FTP
        uses: locaweb/ftp-deploy@1.0.0
        with:
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USER }}
          password: ${{ secrets.PASS }}
          localDir: backend/public
          remoteDir: public_html
