name: Deploy Frontend + Backend via FTP Locaweb

on:
  push:
    branches:
      - main

jobs:
  deploy-frontend:
    name: Deploy Frontend React
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Build React app
        working-directory: frontend
        run: |
          npm install
          npm run build

      - name: Upload frontend via FTP
        uses: locaweb/ftp-deploy@1.0.0
        with:
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USER }}
          password: ${{ secrets.PASS }}
          localDir: frontend/dist

  deploy-backend:
    name: Deploy Backend PHP
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Upload backend PHP via FTP
        uses: locaweb/ftp-deploy@1.0.0
        with:
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USER }}
          password: ${{ secrets.PASS }}
          localDir: backend/app
          remoteDir: public_html/app
