name: Deploy Frontend + Backend via FTP Locaweb

on:
  push:
    branches:
      - main

jobs:
  deploy-frontend:
    name: Deploy Frontend React
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Build React app
        working-directory: frontend
        run: |
          npm install
          npm run build

      - name: Upload frontend via FTP
        uses: locaweb/ftp-deploy@1.0.0
        with:
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USER }}
          password: ${{ secrets.PASS }}
          localDir: frontend/dist
          remoteDir: public_html

  deploy-backend:
    name: Deploy Backend PHP
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Instalar dependências PHP (composer install)
        run: composer install --no-dev --optimize-autoloader

      - name: Criar arquivo .env dentro de backend/app
        run: |
          echo "DB_HOST=${{ secrets.DB_HOST }}" > backend/app/.env
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> backend/app/.env
          echo "DB_USER=${{ secrets.DB_USER }}" >> backend/app/.env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> backend/app/.env
          echo "API_KEY=${{ secrets.API_KEY }}" >> backend/app/.env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> backend/app/.env

      - name: Upload backend/app (com .env) via FTP
        uses: locaweb/ftp-deploy@1.0.0
        with:
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USER }}
          password: ${{ secrets.PASS }}
          localDir: backend/app
          remoteDir: app

      - name: Upload vendor/ via FTP
        uses: locaweb/ftp-deploy@1.0.0
        with:
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USER }}
          password: ${{ secrets.PASS }}
          localDir: vendor
          remoteDir: vendor

      - name: Upload index.php via FTP
        uses: locaweb/ftp-deploy@1.0.0
        with:
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USER }}
          password: ${{ secrets.PASS }}
          localDir: backend/public
          remoteDir: public_html
